name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Build
        run: make nuget config=Release version=${GITHUB_REF#refs/tags/} 

      - name: Test
        run: make test config=Release

      - name: Upload nuget
        uses: actions/upload-artifact@v1
        with:
            name: nuget
            path: ./nuget

  publish:
    if: contains(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # first download artifacts
      - name: Download nuget artifact
        uses: actions/download-artifact@v1
        with:
            name: nuget

      - name: publish nuget
        run: make publish nugetkey=${{secrets.NUGET_KEY}}
